name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_BRANCH: ${{ secrets.BRANCH != '' && secrets.BRANCH || 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          DEPLOY_BRANCH: 'main'
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "➡️ Accessing directory..."
            cd $TARGET_DIR

            echo "➡️ Updating code..."
            git fetch --all
            git checkout $DEPLOY_BRANCH
            git reset --hard origin/$DEPLOY_BRANCH
            git pull origin $DEPLOY_BRANCH

            echo "➡️ Composer..."
            if command -v php8.4 >/dev/null 2>&1; then
              PHP=php8.4
            else
              PHP=php
            fi

            $PHP /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction

            echo "➡️ Migrations & cache..."
            $PHP artisan migrate --force
            $PHP artisan route:cache || true
            $PHP artisan config:cache || true
            $PHP artisan view:cache || true
            $PHP artisan optimize:clear || true

            echo "✔️ Deploy finished!"
